version: '3'

services:
  app:
    image: bbonkr/resume:1.0.0 # Change 
    ports:
      - 80:3000
    restart: always
    network_mode: bridge
    environment:
      - NEXT_PUBLIC_HOST=
      - GAID=
      - ENDPOINT=
      - ACCESSKEY=
      - API=
      - USERNAME=
      - SENDGRID_SENDER=
      - SENDGRID_EMAIL=
      - SENDGRID_API_KEY=