# 1. Copy docker-compose.dev.yml to docker-compose.yml
# 2. Change image name
# 3. Change port
# 4. Copy .env.sample to .env
# 5. Edit .env
# 6. Build docker image
# 7. Run container with compose (docker-compose up -d)
version: '3'

services:
  app:
    image: docker.io/bbonkr/resume:latest # Change 
    container_name: resume
    ports:
      - 20000:3000
    restart: always
    network_mode: bridge
    environment:
      - TZ=Asia/Seoul
      - NEXT_PUBLIC_HOST=${NEXT_PUBLIC_HOST}
      - NEXT_PUBLIC_GAID=${NEXT_PUBLIC_GAID}
      - NEXT_PUBLIC_CLARITY=${NEXT_PUBLIC_CLARITY}
      - HOST=${HOST}
      - ENDPOINT=${ENDPOINT}
      - ACCESSKEY=${ACCESSKEY}
      - USERNAME=${USERNAME}
      - SENDGRID_SENDER=${SENDGRID_SENDER}
      - SENDGRID_EMAIL=${SENDGRID_EMAIL}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - IMAGE_DOMAINS=${IMAGE_DOMAINS}
    entrypoint: ['npm', 'start']